# Generated by Django 3.1.13 on 2022-10-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_tbl_doctor_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_patient_disease',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tbl_patient_information',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
