# Generated by Django 4.1.1 on 2023-02-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0006_tbl_patient_information_health_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_patient_information',
            name='doc_edu',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
