# Generated by Django 4.1.1 on 2023-02-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0007_tbl_patient_information_doc_edu'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dummy_table',
            fields=[
                ('aadhar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=253)),
            ],
        ),
    ]
