# Generated by Django 4.1.1 on 2023-02-11 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0008_tbl_dummy_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_hospital_register',
            name='user',
        ),
    ]
