# Generated by Django 4.1.1 on 2023-02-11 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HospitalApp', '0009_remove_tbl_hospital_register_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_dummy_table',
        ),
        migrations.AddField(
            model_name='tbl_hospital_register',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
